### ISSUE TITLE
Converts ms word like end quote(”) to �?

### ISSUE THREAD

**Issue by rajugurung** [mycila/license-maven-plugin#100]
I am running version 1.9.0 of this plugin in my project. It adds the license information correctly but what it also does is if it sees any of this curly end quote(”), it converts them to �? What's causing this and what can I do to fix it? 

It does not do anything to the start quote(“).

**Comment by mathieucarbou** [comment]
It's probably an encoding issue. Did you try the encoding setting ?

**Comment by mathieucarbou** [comment]
closing - no answer back.
