### ISSUE TITLE
option to not update headers

### ISSUE THREAD

**Issue by jkatnik** [mycila/license-maven-plugin#102]
Hi

in my project I use Liquibase - it maintains SQL files for changing DB structure.
Liquibase evaluates md5 sums for SQL scripts and if it detects that already applied script has changed it raises an error preventing app startup.

When I change licence template the license-maven-plugin updates license in SQL files which is an issue for me.

I'd like to ask to add configuration parameter instructing plugin to not update files.
Sth like:
`<include update="false">src/**/*.sql</include>`
Best Regards,
  Jarek

**Comment by mathieucarbou** [comment]
You can exclude some patterns using:

```
<excludes>
<exclude>src/**/*.sql<exclude>
<excludes>
```
