### ISSUE TITLE
Custom mapping seems to not honor order from configuration

### ISSUE THREAD

**Issue by shane-hp** [mycila/license-maven-plugin#107]
I am using 2.11 and the mapping configuration is not working as expected and documented. It seems like the mapping is handled in alphabetical order, not configuration order.

If I add a custom mapping like this:

\<mapping>
\<xml.tmpl>XML_STYLE\</xml.tmpl>
\<tmpl>SCRIPT_STYLE\</tmpl>
\</mapping>

The *.tmpl mapping is always chosen for my *xml.tmpl files. I would expect the *xml.tmpl files to match to the *.xml.tmpl mapping, which is XML, not SCRIPT. 

This is how it is described in the documentation: "You can use composed-extensions like *.apt.vm and redefine them, but you will have to nake sure that the mapping of apt.vm is before the mapping of the vm extension. The order in the mapping section is important: extensions seen first take precedence."

I am not a Maven plugin expert with respect to coding one, but it seems like the problem is that the mapping is brought in as a HashMap, which will lose the order. Later on, it is moved to a LinkedHashMap; however, the order is already lost. I am not sure where the configuration is put into alphabetical order, perhaps in the Maven base code for plugins.

From AbstractLicenseMojo line 159 - 160:
@Parameter
public Map<String, String> mapping = new HashMap<String, String>();

I then took a look at the test cases in this plugin to see if I was doing my mapping wrong, but I think the problem is that the test is not catching the issue due to the test case having mappings being "randomly" in alphabetical order, as "apt.vm" comes before "vm" alphabetically. This means that the alphabetical nature will not catch the ordering problem.

**Comment by shane-hp** [comment]
Created PR #108 to possibly fix this issue.

**Comment by shane-hp** [comment]
My research showed that Maven will create a TreeMap for any configurations that are set to be a java.util.Map with the @Parameter. The TreeMap is sorted, hence the alphabetical order of the mappings. The solution seems to be to change the type to a LinkedHashMap and then the order seems to be retained.

**Comment by mathieucarbou** [comment]
Thanks! I'll have a look at your PR when I'll have some time :-)

**Comment by mathieucarbou** [comment]
fixed by #108
