### ISSUE TITLE
Add PERCENT_STYLE for LaTeX

### ISSUE THREAD

**Issue by mirabilos** [mycila/license-maven-plugin#111]
Hi,

please add `PERCENT_STYLE` similar to `PERCENT3_STYLE` except:

- no blank line (only percent sign(s)) before or after
- only one percent sign, not three

Also, please map it to `*.tex`, `*.sty`, and `*.cls` (Teχ/LaTeX) by default.

**Comment by mathieucarbou** [comment]
Are you able to send me a PR or the ligne to put in the header definition file ?
Thanks!

**Comment by mirabilos** [comment]
Hmm, I think we cannot do it with lines before/after… will send.

**Comment by mirabilos** [comment]
… nevermind, got it… testing right now

**Comment by mirabilos** [comment]
I think this will do the trick:

    <?xml version="1.0" encoding="UTF-8"?>
    
    <additionalHeaders>
        <Tex_style>
            <beforeEachLine><![CDATA[% ]]></beforeEachLine>
            <endLine><![CDATA[EOL]]></endLine>
            <firstLineDetectionPattern><![CDATA[^% .*$]]></firstLineDetectionPattern>
            <lastLineDetectionPattern><![CDATA[^% .*$]]></lastLineDetectionPattern>
            <allowBlankLines>false</allowBlankLines>
            <isMultiline>false</isMultiline>
            <padLines>false</padLines>
        </Tex_style>
    </additionalHeaders>
