### ISSUE TITLE
How to actually do a PropertiesProvider?

### ISSUE THREAD

**Issue by mirabilos** [mycila/license-maven-plugin#112]
My current problem is that various files, currently separated by subdirectory, can have differing copyright holders (and years, per file, but we’ll tackle this separately).

I’ve seen this part of the documentation…

> Properties are built per-document. You can provide a dependency JAR file to the plugin which contains an implementation of com.mycila.maven.plugin.license.PropertiesProvider:

… but fail to figure out how to actually use that. My idea was to add a `${copyrightholders}` line to the header, and put into the Map an entry “copyrightholders” which is a string containig the lines, separated by newlines (but not trailed by one), and hope it can be used, possibly based on the `document` path.

However, I have no idea how to “provide a dependency JAR file to the plugin”. I’d write this as one class that implements the PropertiesProvider interface, and drop it into the project, for example into the “test-utils” module, as it’s not needed in prod. But when I do that, I get a cyclic dependency, even if the mycila licence plugin is never run during normal “mvn clean install”, only manually (we just upgraded from `mvn com.mycila.maven-license-plugin:maven-license-plugin:1.9.0:format` to `mvn com.mycila:license-maven-plugin:2.11:format`).

Some guidance for those less experienced in Java™ packaging magic would be appreciated ☺

**Comment by mathieucarbou** [comment]
You have several examples with the modules:

- license-maven-plugin-svn
- license-maven-plugin-git

here: https://github.com/mycila/license-maven-plugin

Basically, the idea is to implement this interface, provides a META-INF/services file and when configuring the plugin, you can add some `<dependencies>` section to the plugin, so that your properties provider is on the plugin's classpath.

**Comment by mirabilos** [comment]
So I need to do a *completely separate* Java project just for the plugin, then reference this?

Is there really no way to pick up a class defined in the “current” project?

(In that case, I’ll probably want to write a plugin that allows for multiple different headers/properties, and reads them from a configuration file in the to-be-applied project… but that’s way more code, and I’m short of time at the moment, so, maybe later.)

**Comment by mathieucarbou** [comment]
There is no way to "pickup" a file in the project currently because the way it works right now, the plugin requires a java file developed that is responsible to provide properties.

I guess what you would like is a sort of that ?

```
<propertyFiles>
    <propertyFile>path/to/additional.properties</propertyFile>
<propertyFiles>
```

**Comment by mirabilos** [comment]
> I guess what you would like is a sort of that ?

No, something *much* more complex. I’ll tackle this when I have some time, as I found another couple of “nice things” I could do this way, and come back to you when I have it working, for review (I’m a programmer since the end of the 1980s, I’ve just managed to avoid Java™ until this year when I need to pick it up for $dayjob) and, if you want, integration into your repository (I don’t mind that, but if you don’t want it, I’d keep maintaining it probably).

**Comment by mathieucarbou** [comment]
No problem :-) 

Let's go! I am always pleased to see new incoming contributions! I already added you to the contributor list.

So let's do this: when your idea will be developed (and tested), you could send a PR for review for this feature. Perhaps you could just rename the title of this issue and re-used it for your use case ?

**Comment by mirabilos** [comment]
I’ll open a PR when the time is right, let’s not clutter the Issues list here.
