### ISSUE TITLE
Missing header if not tabs are set.

### ISSUE THREAD

**Issue by ptahchiev** [mycila/license-maven-plugin#117]
Hello,

I have a `pom.xml` file with perfectly valid license header but when i run `mvn license:check` it tells me the file has no valid license header. The problem, I believe, is that the plugin expects the license to be indented with some spacebars (or tabs). 

Here's my license:

```
  ~ My company
  ~
  ~ Copyright (c) 2010 - 2016 mycompany
  ~ All rights reserved.
  ~
  ~ Text
```

here's my "invalid" pom.xml:

```
<!--
  ~ My company
  ~
  ~ Copyright (c) 2010 - 2016 mycompany
  ~ All rights reserved.
  ~
  ~ Text
  -->
```

and this one the license-plugin recognizes as valid (notice how the license is indented):

```
<?xml version="1.0" encoding="UTF-8"?>
<!--

      ~ My company
      ~
      ~ Copyright (c) 2010 - 2016 mycompany
      ~ All rights reserved.
      ~
      ~ Text

-->
```

**Comment by mathieucarbou** [comment]
Hi @ptahchiev : your license text should only contains raw text and no indentation. This is handled by the plugin.

Also, for the XMl style, if you do not like the "empty" lines, you can redefine the XML style to remove them.
