### ISSUE TITLE
Plugin shows warnings about files without license mapping that are excluded from check

### ISSUE THREAD

**Issue by garagatyi** [mycila/license-maven-plugin#131]
I excluded some files from checking but the plugin still shows warnings in maven logs about these files. 
It would be better to completely ignore these files.

**Comment by garagatyi** [comment]
Is it expected behavior?

**Comment by mathieucarbou** [comment]
Hi @garagatyi : the plugin ignores the excluded file types based on some patterns.
It only logs if it finds some file types that are not supported. Not supported means that you didn't exclude them from the plugin scan, and the plugin does not contain any header style mapping for these file extensions.
