### ISSUE TITLE
Support default copyright format of IntelliJ IDEA

### ISSUE THREAD

**Issue by ljacomet** [mycila/license-maven-plugin#134]
Currently there are issues with the default copyright injection of IntelliJ IDEA, notably on XML files.
It would be great to support these formats.

The IntelliJ IDEA default is:
```
<!--
  ~ Copyright Lorem ipsum
  ~ Lorem ipsum
  -->
```

and it has to be configured to become:
```
<!--
  Copyright Lorem ipsum
  Lorem ipsum
  -->
```
otherwise a license violation is reported.

**Comment by McFoggy** [comment]
Using version `license-maven-plugin:3.0` and the configuration capabilities we can redefine the format for XML files

__idea-license-header-definition.xml__
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<additionalHeaders>
    <ideaxml_style>
        <firstLine><![CDATA[<!--]]></firstLine>
        <beforeEachLine>  ~ </beforeEachLine>
        <endLine><![CDATA[  -->
]]></endLine>
        <skipLine><![CDATA[^<\?xml.*>$]]></skipLine>
        <firstLineDetectionPattern><![CDATA[(\s|\t)*<!--.*$]]></firstLineDetectionPattern>
        <lastLineDetectionPattern><![CDATA[.*-->(\s|\t)*$]]></lastLineDetectionPattern>
        <allowBlankLines>true</allowBlankLines>
        <isMultiline>true</isMultiline>
        <padLines>false</padLines>
    </ideaxml_style>
</additionalHeaders>
```

__configuration in pom__
```xml
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>3.0</version>
    <configuration>
        <header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</header>
        <headerDefinitions>
            <headerDefinition>idea-license-header-definition.xml</headerDefinition>
        </headerDefinitions>
        <mapping>
            <xml>IDEAXML_STYLE</xml>
        </mapping>
        <properties>
            <owner>Somewhere INC.</owner>
            <email>contact@somewhere.com</email>
        </properties>
        <excludes>
            <exclude>**/README</exclude>
            <exclude>src/test/resources/**</exclude>
            <exclude>src/main/resources/**</exclude>
            <exclude>idea-license-header-definition.xml</exclude>
        </excludes>
    </configuration>
    <executions>
        <execution>
            <phase>validate</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

__IDEA configuration__
![image](https://user-images.githubusercontent.com/1119660/52132324-31b12980-263f-11e9-9f43-c11cc6e47914.png)

add the Copyright to the pom.xml file

__check licenses in maven__
pom.xml is checked successfully

![image](https://user-images.githubusercontent.com/1119660/52132435-72a93e00-263f-11e9-8e64-b02e4edcaaf0.png)

**Comment by mathieucarbou** [comment]
@ljacomet @McFoggy : ahah I finally have time to look down the issue list and found this one.

Do you think it is worth adding a new style in the plugin for XML ? I.e. `IDEA_XML_STYLE` ?

**Comment by McFoggy** [comment]
@mathieucarbou I also use intellij. 

> Do you think it is worth adding a new style in the plugin for XML ? I.e. `IDEA_XML_STYLE` ?

Personnaly (and in my company also) on the projects where I use license-maven-plugin I do not configure Intellij to modify the headers ; it is left to the plugin.

**Comment by ljacomet** [comment]
Given that there is a configuration option, I do not think it is worth having a custom format for this. The only thing that might be worth a change would be to allow line prefixes to contain one non-whitespace character.

But I have no idea how complex this could be, and I no longer work on a project that had this issue so can't commit time to help improve the situation.
