### ISSUE TITLE
Goal remove doesn't work for all license texts

### ISSUE THREAD

**Issue by amitbhadra** [mycila/license-maven-plugin#135]
I've tried the goal remove when my license.txt file had something like - _Rubbish License File_
It showed in the log that the headers were removed but the in the files, the header was still there.

Then I tried with a standard header in my license.txt like - _******* ... Copyright information .. *****_ , the remove goal worked perfectly. 

I'm using release 3.0 and all other configurations are fine.

**Comment by mathieucarbou** [comment]
Hi,
Removal is done by detecting a potential existing header. This is done by using keywords and by specifying keywords to look at.

**Comment by mathieucarbou** [comment]
closing this old issue
