### ISSUE TITLE
Question: How to setup aggregate in order to not interfere in files from modules not in reactor ?

### ISSUE THREAD

**Issue by cvgaviao** [mycila/license-maven-plugin#152]
I'm trying to set a parent POM in order to do a check for file's license header on all modules include in that root POM.
My problem is that the plugin is processing files that in my vision it not supposed to do.

Initially I did the following:
```
                 <plugin>
                        <groupId>com.mycila</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <inherited>true</inherited>
                        <executions>
                            <execution>
                                <id>check-header-root-project</id>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                                <phase>process-test-classes</phase>
		                        <configuration>
		                        	<detail>true</detail>
		                        	<aggregate>true</aggregate>
		                        	<useDefaultExcludes>true</useDefaultExcludes>
			                        <includes>
			                            <include>pom.xml</include>
			                            <include>src/main/java/**</include>
			                            <include>src/test/java/**</include>
			                        </includes>
		                        </configuration>
                            </execution>
                        </executions>
                    </plugin>
```
But some how it is not finding any problem in any children module's POM.
If I change the config to `<include>*\pom.xml</include>` it will take all directories including those that are not part of the root reactor.
am I missing something here ?

**Comment by mathieucarbou** [comment]
you cannot used `aggregate>true</aggregate>` with `<inherited>true</inherited>` : even if technically this is allowed, logically it does not make any sense since al sub modules would try to run the license check again with all their sub modules again.

aggregate treats the root project as 1 module. All the files within it will be checked (subject to include/exclude rules)
