### ISSUE TITLE
Be able to silence the license output logging

### ISSUE THREAD

**Issue by bbottema** [mycila/license-maven-plugin#159]
I have a multimodule project with maaaany classes. My build log is completely polluted with all the format/remove statements per file.

It would be nice to be able to suppress that output in case of success.

**Comment by McFoggy** [comment]
can't you just skip the execution ?

**Comment by bbottema** [comment]
@McFoggy Are you suggesting that the solution to silencing the verbose logging output is to not use the plugin at all? Then no, I can't just skip the execution :)

**Comment by McFoggy** [comment]
so you would expect just a kind of 'resume' instead of the full log, right?

**Comment by bbottema** [comment]
Something like a 'quiet' property similar to the javadoc-plugin, assertj-plugin etc etc

**Comment by McFoggy** [comment]
did you already tried the [quiet](https://github.com/mycila/license-maven-plugin/blob/master/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java#L224) property of the plugin?

You should be able to set it via plugin configuration:

```
<plugin>
    <groupId>com.mycila</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>X.Y.ga</version>
    <configuration>
        <quiet>true</quiet>
...
</plugin>
```

or override via a runtime property `license.quiet` as in `mvn license:check -Dlicense.quiet=true`

**Comment by bbottema** [comment]
Yeah I found that property I don't remember if I'm still having a problem, I'll close this issue until I remember :P
