### ISSUE TITLE
Failed to execute goal com.mycila:license-maven-plugin:3.0:check (license-headers) on project validation-api

### ISSUE THREAD

**Issue by AnujDwiv** [mycila/license-maven-plugin#162]
while compiling the source code of Validation API 2.0.0 Final. Build is failing with the following error : 

[ERROR] Failed to execute goal **com.mycila:license-maven-plugin:3.0:check** (license-headers) on project **validation-api**: Execution license-headers of goal com.mycila:license-maven-plugin:3.0:check failed: **Error creating XMLDoc. Please verify that the input source can be read and is well formed. - Content is not allowed in prolog**. -> [Help 1]**

**Comment by mathieucarbou** [comment]
your XML document might contain an incorrect character at the beginning.
