### ISSUE TITLE
Allow for passing header text as text in plugin not only file

### ISSUE THREAD

**Issue by bartekkocik** [mycila/license-maven-plugin#181]
For multi module Maven project I would like to have possibility to configure in parent project plugin with licence text definition which can be inherited without relative path to licence file and be able to use this configuration from any subprojects. Now when I'm building subproject and configuration was in parent pom I'm getting error that licence file can't be found. Licence file path is relative (and can't be absolute) so execution from different places will not work.
Solution would be to add parameter by which we could pass license text like
<headerText>my text line 1\nmy text line 2</headerText>
It doesn't need to pass html tags through this parameter which probably would make it difficult.

Example setup:

--parent project (build works from here)
    |--sub-project1 (build not works from here)
    |--sub-project2 (build not works from here)
    |--copyright.txt

pluing configuration on parent project pom          

            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <licenseSets>
                        <licenseSet>
                            <header>copyright.txt</header>
                            <excludes>
                                <exclude>**/README</exclude>
                                <exclude>**/*.groovy</exclude>
                                <exclude>**/pom.xml</exclude>
                                <exclude>**/resources/**</exclude>
                                <exclude>**/.helmignore</exclude>
                                <exclude>**/*.yml</exclude>
                                <exclude>**/*.yaml</exclude>
                                <exclude>**/*.json</exclude>
                                <exclude>**/*.tpl</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by mathieucarbou** [comment]
You already can. You can use the aggregate option to true and inherited maven option of the plugin to false.

**Comment by mathieucarbou** [comment]
you can even use inlineHeader option.
