### ISSUE TITLE
Please release 4.0.rc2 to solve some of the repeated open issues / allow for further testing

### ISSUE THREAD

**Issue by hazendaz** [mycila/license-maven-plugin#184]
Can we get 4.0.rc2 released so we can further test?  I think a few folks are running into same issues I did which I think are all resolved in 4.0.rc2.  I'd like to test more in large scale projects and I cannot bring in snapshots or clone as needed in the case I need to test.  I'm sure others are in same restricted boat I am :)

**Comment by mathieucarbou** [comment]
Yes will do right away!

**Comment by hazendaz** [comment]
Great @mathieucarbou, I'll jump on testing this pretty heaving this coming week and will report back any findings :)  Appreciate it.

**Comment by mathieucarbou** [comment]
done! will be available soon.

**Comment by hazendaz** [comment]
Sweet!  Thanks so much!
