### ISSUE TITLE
The plugin doesn't support parallel build

### ISSUE THREAD

**Issue by sdumitriu** [mycila/license-maven-plugin#39]
Running:

    mvn clean install -T 2C

Build failed with:

> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.6:check (default) on project XYZ: Execution default of goal com.mycila:license-maven-plugin:2.6:check failed: Error creating XMLDoc. Please verify that the input source can be read and is well formed: FWK005 parse may not be called while parsing. -> [Help 1]

**Comment by mathieucarbou** [comment]
Hi,

I think I've found it.

```
com.mycila.xmltool.XMLDocBuilder.from(Lorg/xml/sax/InputSource;Z)Lcom/mycila/xmltool/XMLTag;+5
com.mycila.xmltool.XMLDoc.from(Lorg/xml/sax/InputSource;Z)Lcom/mycila/xmltool/XMLTag;+9
```

The license plugin is using a library which creates an XML document. This library had a thread-safety issue regarding XML document creation. 

I'll try to upgrade to the new version.
