### ISSUE TITLE
Error configuring includes

### ISSUE THREAD

**Issue by bobvarghese** [mycila/license-maven-plugin#52]
I tried setting a pattern for includes but the plugin doesn't seem to like it.

It throws the following error:
 Cannot assign configuration entry 'includes' with value '**/*java' of type java.lang.String to property of type java.lang.String[]

maven plugin config snippet: 
<configuration>
	<includes>**/*java</includes>
</configuration>

**Comment by mathieucarbou** [comment]
This is a Maven-related error because of a wrong format of your xml file. try with:
```
<includes>
<include>...</include>
</includes>
```
