### ISSUE TITLE
logs "Checking licenses..." when -Dlicense.skip=true

### ISSUE THREAD

**Issue by criffle** [mycila/license-maven-plugin#67]
When running license:check with the -Dlicense.skip=true flag set, the logging outputs:  "Checking licenses..." even though licenses are not being checked.

I think the issue is in the class:  LicenseCheckMojo - on line 41

https://github.com/mycila/license-maven-plugin/blob/1a08ad3af8c1543e397b9d5c4bfac0c7b13f49c3/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java

Thanks!

**Comment by mathieucarbou** [comment]
I need to review also other mojo to avoid logging when skip is set to true
