### ISSUE TITLE
enforce project EOL to be correct regardless of user GIT settings

### ISSUE THREAD

**Issue by McFoggy** [mycila/license-maven-plugin#76]
We should find a way to enforce some rules at project level so that whatever the default global git configuration of a user is, the project works as expected.

Today (commit [dbc060a5297228055ce791ad2af4027da6e37a95](https://github.com/mycila/license-maven-plugin/commit/dbc060a5297228055ce791ad2af4027da6e37a95)), if you are on a windows machine and you applied different GIT recommandations ([GIT SCM book](http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration), [Github documentation](https://help.github.com/articles/dealing-with-line-endings/)) by setting `git config --global core.autocrlf true`
then the project does not build correctly: tests in UpdateMojoTest & RemoveMojoTest are failing because they rely on specific `\n` line ending.

At least we should investigate if we could not enforce, using git functionnalities, project specific rules that would override user settings.

**Comment by mathieucarbou** [comment]
As I already said, `core.autocrlf` should NEVER be true for the simple reason that it is a host-specific config which modify project files.
If prject files are modified, it is a NORMAL behavior for tests to fail.

**Comment by mathieucarbou** [comment]
I'll add that there is a way to modify this property at a project level by editing the file `.git/config`.

**Comment by McFoggy** [comment]
I do not understand why you are closing this directly without letting anyone including me to lookup & provide a way to make this transparent?
From what I see on projects where EOL characters matter, they provide PROJECT SPECIFIC rules via a .gitattributes file.
If there is a way to do this clean, why do you refuse to at least investigate it?

Please reconsider reopening the issue until a real analysis of existing possibilities is done.

**Comment by McFoggy** [comment]
>  I'll add that there is a way to modify this property at a project level by editing the file .git/config

but that means a manual step after checking out the project.
Really I am convinced that if a clean setup is possible then we should try it.

**Comment by mathieucarbou** [comment]
Sorry! yes it should not be closed! I misunderstood the issue description. If here is some way to set the `autocrlf` setting specifically for a project, yes it would do the trick.
I'd like also to avoid placing a `.gitattributes` file which treat all files as binary ;-)
