### ISSUE TITLE
no command for only add missing licenses

### ISSUE THREAD

**Issue by mbiarnes** [mycila/license-maven-plugin#81]
In http://code.mycila.com/license-maven-plugin it says: 
format: add headers if missing.
On the same page it says below: 
license:format: add the license header when missing. If a header is existing, it is updated to the new one.

I used mvn license:format and it added me licenses where i did not have any, but it also updated licenses I already had.
This changed i.e the years I had before in my existing licenses by the year of the new license.

Is there a command where I only can add licenses to files without any - without updating existing ones?

**Comment by mathieucarbou** [comment]
Hi,

There is no such feature yet, but It would be nice to had it and not complicated to implement I think.

I won't be able to implement it during the following weeks - someone could send a PR. Otherwise I should be able to implement it near mid-july.

**Comment by christiangalsterer** [comment]
Hi,
+1 from my side for this feature. I think it is a common use case to have a license similar to the following one where for existing headers the year should not be updated.

```java
/*
 * Copyright (c) 2015. All rights reserved.
*/
```

I think https://github.com/mycila/license-maven-plugin/issues/51 addresses the same problem.
Do you have an updated view when 2.12 will be released? If you are interested in support to implement this feature and can provide some ideas where and how to change the code I might be able to help.

**Comment by mikulucky** [comment]
This can be resolved without any changes. Within your configuration block simply add the following 
```xml
<skipExistingHeaders>true</skipExistingHeaders>
```
Here is an example of my configuration

```xml
<plugin>
  <groupId>com.mycila</groupId>`
  <artifactId>license-maven-plugin</artifactId>
  <version>2.11</version>
    <configuration>
      <header>com/mycila/maven/plugin/license/templates/MIT.txt</header>
      <properties>
        <owner>Owner Name</owner>
        <email>owner@something.com</email>
      </properties>
      <skipExistingHeaders>true</skipExistingHeaders>
    </configuration>
    <executions>
      <execution>
        <id>install-format</id>
        <phase>install</phase>
        <goals>
          <goal>format</goal>
        </goals>
      </execution>
    </executions>        
</plugin>
```

**Comment by mathieucarbou** [comment]
thanks @mikulucky  - forgot this one ;-)
