### ISSUE TITLE
Ability to specify license header inline

### ISSUE THREAD

**Issue by roxspring** [mycila/license-maven-plugin#82]
I need to specify a simple one-line license statement and use it for a multi-module build:

    Copyright (c) ${year} ${organizationName} All Rights Reserved

Is it possible to specify this pattern inline so that there's no dependency on pulling the license from some file path?

(Alternatively would there be interested in a simple "ALL-RIGHTS-RESERVED" license since I imagine this is a fairly regular requirement for closed source shops)

**Comment by mathieucarbou** [comment]
Agree. 
We'll see how to implement this. We could provide both such template, plus a new option to specify the raw header text.

**Comment by sadentc** [comment]
+1.

Pulling license header from a file get really messing when working with projects with sub-modules.

**Comment by heapifyman** [comment]
+1

**Comment by mathieucarbou** [comment]
Implemented with `inlineHeader` setting, or `-Dlicense.inlineHeader`.

**Comment by sadentc** [comment]
:100:
