### ISSUE TITLE
license.header path inherited from parent pom not adjusted for mvn modules.

### ISSUE THREAD

**Issue by 243826** [mycila/license-maven-plugin#83]
I have a project where in the parent pom I have following configuration:

```
   <plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>2.11</version>
        <configuration>
          <header>license.txt</header>
          // rest of the stuff here
```

and there are child modules in subdirectories of the directory holding the parent pom. When the project is built in its entirety from the parent folder, the license check works just fine cause it's able to resolve license.txt.

But if I chdir into individual subfolder, and try to license:check, the check fails. It should take into consideration the `relativePath` pom property if the license file path is relative to the filesystem.

Please correct my use case if my mvn knowledge sucks.

**Comment by mathieucarbou** [comment]
Hi,
The plugin should not be inherited to child modules in your case. Maven has an attribute for this: `<inherited>false</inherited>` under the `<plugin>` section.
Let us know if this solves your problem :-)

**Comment by 243826** [comment]
I get the following error now:

[INFO] --- license-maven-plugin:2.11:check (default-cli) @ dt-common ---
[INFO] Checking licenses...
[WARNING] No header file specified to check for license


The check does not emit this error at the top level. dt-common is a
submodule of the parent project.

--
Chetan

**Comment by mathieucarbou** [comment]
<header>license.txt</header> searches for a file. So this file should be in all modules. You should use a jar dependency set in the plugin for your use case I think...

**Comment by mathieucarbou** [comment]
Note: will be closed in a few days if i have no feedback
