### ISSUE TITLE
excludes appears to be ignored

### ISSUE THREAD

**Issue by dhoffer** [mycila/license-maven-plugin#90]
I have a requirement to include most files but to exclude some in particular folders so I have configured like this:

```
 <excludes>
    <exclude>**/soap/**/*.*</exclude>
    <exclude>**/database/modeler/**/*.*</exclude>
 </excludes>
 <includes>
    <include>**/com/foobar/**/*.java</include>
    <include>**/*.bat</include>
    <include>**/*.xml</include>
 </includes>
```

Yet the excluded folders are not being excluded.

**Comment by lhanson** [comment]
I have a similar issue. Running version 1.9.0, the plugin is flagging .idea/workspace.xml as not containing a valid header. My workaround is to explicitly exclude .idea, even though it appears to be mentioned in [Default.java](https://github.com/mycila/license-maven-plugin/blob/master/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java), e.g.

    <configuration>
        <excludes>
            <exclude>.idea/**</exclude>
        </excludes>
    </configuration>

**Comment by mathieucarbou** [comment]
.idea exclusion works fine - I think it could be something else.

Can you either add a unit test as a PR to reproduce the issue, or give me a sample maven project reproducing this ?

**Comment by mathieucarbou** [comment]
Can you reproduce that with version 2.11 ? Can you send a unit test please ?

**Comment by mathieucarbou** [comment]
Note: will be closed in a few days if i have no feedback
