### ISSUE TITLE
exclue font file

### ISSUE THREAD

**Issue by pinghe** [mycila/license-maven-plugin#92]
https://github.com/mycila/license-maven-plugin/blob/master/license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/Default.java

add

~~~~
"**/*.svg",
"**/*.eot",
"**/*.ttf",
"**/*.woff",
~~~~

        // Office documents add
~~~
"**/*.xlsx",
"**/*.docx",
"**/*.ppt",
"**/*.pptx",
~~~

**Comment by mathieucarbou** [comment]
Please create a PR and update the tests...
