### ISSUE TITLE
Adding support for all Eclipse project

### ISSUE THREAD

**Issue by flefevre** [mycila/license-maven-plugin#93]
Hello
at first, thanks for this great plugin !

I have some difficulties to make it work on Eclipse projects that have EPL.
The pattern of the offcial license is here: http://www.eclipse.org/legal/copyrightandlicensenotice.php

/*******************************************************************************
 * Copyright (c) {DATE} {INITIAL COPYRIGHT OWNER} {OTHER COPYRIGHT OWNERS}.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    {INITIAL AUTHOR} - initial API and implementation and/or initial documentation
 *******************************************************************************/

We have many, many projects where we would like to make a check.
For instance Papyrus-SysML project https://git.eclipse.org/c/papyrus/org.eclipse.papyrus-sysml.git/

Initial header coul have several {DATE} or different {INITIAL COPYRIGHT OWNER}

So can I tell your plugin to respect the provided header template?
Thanks
Francois

**Comment by mathieucarbou** [comment]
I think you'll have to define your own template with the XML definition file.

**Comment by mathieucarbou** [comment]
Note: will be closed in a few days if i have no feedback
