### ISSUE TITLE
Support for mulitiple years in header based on git log

### ISSUE THREAD

**Issue by arulrajnet** [mycila/license-maven-plugin#95]
Include multiple years in the copyright header, indicating the various years in which various material in the overall work was first published. So, if the file was originally created in 1998 and new copyrightable content was added in 2000, the year portion of the copyright header might be “1998, 2000.” If new content was added in 1998, 2000, and 2004, the year date might be “1998, 2000, 2004”

Refer http://techwhirl.com/updating-copyright-notices/

**Comment by mathieucarbou** [comment]
This issue is related to https://github.com/mycila/license-maven-plugin/pull/145 and can be solved in 4.0
