### ISSUE TITLE
maven doc main page do not shows goals

### ISSUE THREAD

**Issue by cvgaviao** [mycila/license-maven-plugin#97]
If you follow this [link](http://code.mycila.com/license-maven-plugin/reports/2.3/index.html) you can't see anything other than some project details that do not help who would need to learn how to use this tool

**Comment by mathieucarbou** [comment]
links have been changed to the plugin info page.

I.e.: http://code.mycila.com/license-maven-plugin/reports/3.0.rc1/plugin-info.html
