### ISSUE TITLE
Want to skip <!DOCTYPE.*> in HTML file header

### ISSUE THREAD

**Issue by AbhijitVyas** [mycila/license-maven-plugin#98]
Hello,

This is an issue I have been facing since last couple of days. I want to skip my HTML file tag "**<!DOCTYPE.*>**" and insert header in next line. I tried to create my own customHeader.xml file where, I have defined "**skipLine : <![CDATA[<\!DOCTYPE.*>]]> **". Now the problem is, since this setting file is using "xml_style", all the other xml files are haing problem with their headers. New header in all xml files is added before "<?xml version="1.0" encoding="UTF-8"?>", which results into an error with my POM.xml.

If someone has solution to this problem, please let me know. 

Cheers,
Abhijit

**Comment by mathieucarbou** [comment]
It is possible to just redefine the mapping between extensions and header types, and just for xml, you could redefine a custom header type.

**Comment by mathieucarbou** [comment]
will close, will be resolved by #38 otherwise.
